// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open FSharp.Text.Lexing
open FSharp.Text.Parsing.ParseHelpers
# 1 "Parser.fsy"

open SVProject1.Ast

# 10 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | LPAREN
  | RPAREN
  | IF
  | THEN
  | ELSE
  | UNDEF
  | COLON
  | SEMICOLON
  | COMMA
  | EQ
  | PLUS
  | MINUS
  | MULT
  | ID of (string)
  | Number of (int)
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_LPAREN
    | TOKEN_RPAREN
    | TOKEN_IF
    | TOKEN_THEN
    | TOKEN_ELSE
    | TOKEN_UNDEF
    | TOKEN_COLON
    | TOKEN_SEMICOLON
    | TOKEN_COMMA
    | TOKEN_EQ
    | TOKEN_PLUS
    | TOKEN_MINUS
    | TOKEN_MULT
    | TOKEN_ID
    | TOKEN_Number
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startprog
    | NONTERM_prog
    | NONTERM_funcn
    | NONTERM_params
    | NONTERM_expr
    | NONTERM_factor
    | NONTERM_paramExpr
    | NONTERM_func
    | NONTERM_decn

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | LPAREN  -> 1 
  | RPAREN  -> 2 
  | IF  -> 3 
  | THEN  -> 4 
  | ELSE  -> 5 
  | UNDEF  -> 6 
  | COLON  -> 7 
  | SEMICOLON  -> 8 
  | COMMA  -> 9 
  | EQ  -> 10 
  | PLUS  -> 11 
  | MINUS  -> 12 
  | MULT  -> 13 
  | ID _ -> 14 
  | Number _ -> 15 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_LPAREN 
  | 2 -> TOKEN_RPAREN 
  | 3 -> TOKEN_IF 
  | 4 -> TOKEN_THEN 
  | 5 -> TOKEN_ELSE 
  | 6 -> TOKEN_UNDEF 
  | 7 -> TOKEN_COLON 
  | 8 -> TOKEN_SEMICOLON 
  | 9 -> TOKEN_COMMA 
  | 10 -> TOKEN_EQ 
  | 11 -> TOKEN_PLUS 
  | 12 -> TOKEN_MINUS 
  | 13 -> TOKEN_MULT 
  | 14 -> TOKEN_ID 
  | 15 -> TOKEN_Number 
  | 18 -> TOKEN_end_of_input
  | 16 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startprog 
    | 1 -> NONTERM_prog 
    | 2 -> NONTERM_funcn 
    | 3 -> NONTERM_funcn 
    | 4 -> NONTERM_funcn 
    | 5 -> NONTERM_params 
    | 6 -> NONTERM_params 
    | 7 -> NONTERM_expr 
    | 8 -> NONTERM_expr 
    | 9 -> NONTERM_expr 
    | 10 -> NONTERM_expr 
    | 11 -> NONTERM_factor 
    | 12 -> NONTERM_factor 
    | 13 -> NONTERM_factor 
    | 14 -> NONTERM_factor 
    | 15 -> NONTERM_factor 
    | 16 -> NONTERM_factor 
    | 17 -> NONTERM_paramExpr 
    | 18 -> NONTERM_paramExpr 
    | 19 -> NONTERM_func 
    | 20 -> NONTERM_func 
    | 21 -> NONTERM_decn 
    | 22 -> NONTERM_decn 
    | 23 -> NONTERM_decn 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 18 
let _fsyacc_tagOfErrorTerminal = 16

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | LPAREN  -> "LPAREN" 
  | RPAREN  -> "RPAREN" 
  | IF  -> "IF" 
  | THEN  -> "THEN" 
  | ELSE  -> "ELSE" 
  | UNDEF  -> "UNDEF" 
  | COLON  -> "COLON" 
  | SEMICOLON  -> "SEMICOLON" 
  | COMMA  -> "COMMA" 
  | EQ  -> "EQ" 
  | PLUS  -> "PLUS" 
  | MINUS  -> "MINUS" 
  | MULT  -> "MULT" 
  | ID _ -> "ID" 
  | Number _ -> "Number" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | LPAREN  -> (null : System.Object) 
  | RPAREN  -> (null : System.Object) 
  | IF  -> (null : System.Object) 
  | THEN  -> (null : System.Object) 
  | ELSE  -> (null : System.Object) 
  | UNDEF  -> (null : System.Object) 
  | COLON  -> (null : System.Object) 
  | SEMICOLON  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | EQ  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | MULT  -> (null : System.Object) 
  | ID _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Number _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us;65535us;1us;65535us;0us;1us;2us;65535us;0us;2us;19us;18us;2us;65535us;10us;14us;21us;22us;12us;65535us;3us;4us;12us;13us;16us;17us;32us;24us;33us;25us;34us;26us;39us;27us;41us;28us;42us;29us;43us;30us;44us;31us;46us;31us;12us;65535us;3us;23us;12us;23us;16us;23us;32us;23us;33us;23us;34us;23us;39us;23us;41us;23us;42us;23us;43us;23us;44us;23us;46us;23us;2us;65535us;44us;45us;46us;48us;12us;65535us;3us;38us;12us;38us;16us;38us;32us;38us;33us;38us;34us;38us;39us;38us;41us;38us;42us;38us;43us;38us;44us;38us;46us;38us;2us;65535us;5us;6us;55us;54us;|]
let _fsyacc_sparseGotoTableRowOffsets = [|0us;1us;3us;6us;9us;22us;35us;38us;51us;|]
let _fsyacc_stateToProdIdxsTableElements = [| 1us;0us;1us;0us;2us;1us;4us;1us;1us;4us;1us;8us;9us;10us;1us;1us;2us;1us;23us;1us;1us;1us;1us;2us;2us;3us;2us;2us;3us;1us;2us;1us;2us;4us;2us;8us;9us;10us;1us;3us;1us;3us;1us;3us;4us;3us;8us;9us;10us;2us;4us;4us;1us;4us;2us;5us;6us;1us;6us;1us;6us;1us;7us;4us;8us;8us;9us;10us;4us;8us;9us;9us;10us;4us;8us;9us;10us;10us;4us;8us;9us;10us;15us;4us;8us;9us;10us;16us;4us;8us;9us;10us;16us;4us;8us;9us;10us;16us;5us;8us;9us;10us;17us;18us;1us;8us;1us;9us;1us;10us;1us;11us;1us;12us;3us;13us;19us;20us;1us;14us;1us;15us;1us;15us;1us;16us;1us;16us;1us;16us;1us;18us;1us;18us;2us;19us;20us;1us;19us;1us;20us;1us;20us;2us;21us;22us;2us;21us;22us;1us;21us;1us;22us;2us;23us;23us;1us;23us;|]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us;2us;4us;7us;9us;14us;16us;19us;21us;23us;26us;29us;31us;33us;38us;40us;42us;44us;49us;52us;54us;57us;59us;61us;63us;68us;73us;78us;83us;88us;93us;98us;104us;106us;108us;110us;112us;114us;118us;120us;122us;124us;126us;128us;130us;132us;134us;137us;139us;141us;143us;146us;149us;151us;153us;156us;|]
let _fsyacc_action_rows = 56
let _fsyacc_actionTableElements = [|1us;32768us;14us;9us;0us;49152us;2us;32768us;8us;3us;9us;19us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;4us;32768us;8us;5us;11us;32us;12us;33us;13us;34us;1us;32768us;14us;50us;2us;32768us;8us;7us;9us;55us;1us;32768us;0us;8us;0us;16385us;1us;32768us;1us;10us;2us;32768us;2us;11us;14us;20us;1us;32768us;10us;12us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;3us;16386us;11us;32us;12us;33us;13us;34us;1us;32768us;2us;15us;1us;32768us;10us;16us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;3us;16387us;11us;32us;12us;33us;13us;34us;1us;16388us;9us;19us;1us;32768us;14us;9us;1us;16389us;9us;21us;1us;32768us;14us;20us;0us;16390us;0us;16391us;1us;16392us;13us;34us;1us;16393us;13us;34us;0us;16394us;4us;32768us;2us;40us;11us;32us;12us;33us;13us;34us;4us;32768us;4us;42us;11us;32us;12us;33us;13us;34us;4us;32768us;5us;43us;11us;32us;12us;33us;13us;34us;3us;16400us;11us;32us;12us;33us;13us;34us;4us;16401us;9us;44us;11us;32us;12us;33us;13us;34us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;0us;16395us;0us;16396us;1us;16397us;1us;46us;0us;16398us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;0us;16399us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;5us;32768us;1us;39us;3us;41us;6us;36us;14us;37us;15us;35us;0us;16402us;6us;32768us;1us;39us;2us;47us;3us;41us;6us;36us;14us;37us;15us;35us;0us;16403us;1us;32768us;2us;49us;0us;16404us;1us;32768us;10us;51us;2us;32768us;6us;53us;15us;52us;0us;16405us;0us;16406us;1us;16407us;9us;55us;1us;32768us;14us;50us;|]
let _fsyacc_actionTableRowOffsets = [|0us;2us;3us;6us;12us;17us;19us;22us;24us;25us;27us;30us;32us;38us;42us;44us;46us;52us;56us;58us;60us;62us;64us;65us;66us;68us;70us;71us;76us;81us;86us;90us;95us;101us;107us;113us;114us;115us;117us;118us;124us;125us;131us;137us;143us;149us;150us;157us;158us;160us;161us;163us;166us;167us;168us;170us;|]
let _fsyacc_reductionSymbolCounts = [|1us;7us;5us;6us;3us;1us;3us;1us;3us;3us;3us;1us;1us;1us;1us;3us;6us;1us;3us;3us;4us;3us;3us;3us;|]
let _fsyacc_productionToNonTerminalTable = [|0us;1us;2us;2us;2us;3us;3us;4us;4us;4us;4us;5us;5us;5us;5us;5us;5us;6us;6us;7us;7us;8us;8us;8us;|]
let _fsyacc_immediateActions = [|65535us;49152us;65535us;65535us;65535us;65535us;65535us;65535us;16385us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;16390us;16391us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;65535us;16395us;16396us;65535us;16398us;65535us;16399us;65535us;65535us;65535us;65535us;16402us;65535us;16403us;65535us;16404us;65535us;65535us;16405us;16406us;65535us;65535us;|]
let _fsyacc_reductions = lazy [|
# 186 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> SVProject1.Ast.Program in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : 'gentype__startprog));
# 195 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_funcn in
            let _3 = parseState.GetInput(3) :?> 'gentype_expr in
            let _5 = parseState.GetInput(5) :?> 'gentype_decn in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 20 "Parser.fsy"
                                                                               Program(_1, _3, _5) 
                   )
# 20 "Parser.fsy"
                 : SVProject1.Ast.Program));
# 208 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _5 = parseState.GetInput(5) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "Parser.fsy"
                                                                               [FuncDec(_1, [], _5)] 
                   )
# 23 "Parser.fsy"
                 : 'gentype_funcn));
# 220 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_params in
            let _6 = parseState.GetInput(6) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 24 "Parser.fsy"
                                                                               [FuncDec(_1, _3, _6)] 
                   )
# 24 "Parser.fsy"
                 : 'gentype_funcn));
# 233 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_funcn in
            let _3 = parseState.GetInput(3) :?> 'gentype_funcn in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 25 "Parser.fsy"
                                                                               _1 @ _3 
                   )
# 25 "Parser.fsy"
                 : 'gentype_funcn));
# 245 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 "Parser.fsy"
                                                                               [_1] 
                   )
# 28 "Parser.fsy"
                 : 'gentype_params));
# 256 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_params in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "Parser.fsy"
                                                                               _1 :: _3 
                   )
# 29 "Parser.fsy"
                 : 'gentype_params));
# 268 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_factor in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "Parser.fsy"
                                                                               _1 
                   )
# 32 "Parser.fsy"
                 : 'gentype_expr));
# 279 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "Parser.fsy"
                                                                               EOp(_1, Plus, _3) 
                   )
# 33 "Parser.fsy"
                 : 'gentype_expr));
# 291 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "Parser.fsy"
                                                                               EOp(_1, Minus, _3) 
                   )
# 34 "Parser.fsy"
                 : 'gentype_expr));
# 303 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 35 "Parser.fsy"
                                                                               EOp(_1, Mult, _3) 
                   )
# 35 "Parser.fsy"
                 : 'gentype_expr));
# 315 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> int in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 38 "Parser.fsy"
                                                                               ENum(Some _1) 
                   )
# 38 "Parser.fsy"
                 : 'gentype_factor));
# 326 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "Parser.fsy"
                                                                               ENum(None) 
                   )
# 39 "Parser.fsy"
                 : 'gentype_factor));
# 336 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "Parser.fsy"
                                                                               EVar _1 
                   )
# 40 "Parser.fsy"
                 : 'gentype_factor));
# 347 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_func in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "Parser.fsy"
                                                                               _1 
                   )
# 41 "Parser.fsy"
                 : 'gentype_factor));
# 358 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 42 "Parser.fsy"
                                                                               _2 
                   )
# 42 "Parser.fsy"
                 : 'gentype_factor));
# 369 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _2 = parseState.GetInput(2) :?> 'gentype_expr in
            let _4 = parseState.GetInput(4) :?> 'gentype_expr in
            let _6 = parseState.GetInput(6) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 43 "Parser.fsy"
                                                                               ECond(_2, _4, _6) 
                   )
# 43 "Parser.fsy"
                 : 'gentype_factor));
# 382 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "Parser.fsy"
                                                                               [_1] 
                   )
# 46 "Parser.fsy"
                 : 'gentype_paramExpr));
# 393 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_expr in
            let _3 = parseState.GetInput(3) :?> 'gentype_paramExpr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "Parser.fsy"
                                                                               [_1] @ _3 
                   )
# 47 "Parser.fsy"
                 : 'gentype_paramExpr));
# 405 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "Parser.fsy"
                                                                               EFunc(_1, []) 
                   )
# 50 "Parser.fsy"
                 : 'gentype_func));
# 416 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _3 = parseState.GetInput(3) :?> 'gentype_paramExpr in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "Parser.fsy"
                                                                               EFunc(_1, _3) 
                   )
# 51 "Parser.fsy"
                 : 'gentype_func));
# 428 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            let _3 = parseState.GetInput(3) :?> int in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "Parser.fsy"
                                                                               [Def(_1, Some _3)] 
                   )
# 54 "Parser.fsy"
                 : 'gentype_decn));
# 440 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> string in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "Parser.fsy"
                                                                               [Def(_1, None)] 
                   )
# 55 "Parser.fsy"
                 : 'gentype_decn));
# 451 "Parser.fs"
        (fun (parseState : FSharp.Text.Parsing.IParseState) ->
            let _1 = parseState.GetInput(1) :?> 'gentype_decn in
            let _3 = parseState.GetInput(3) :?> 'gentype_decn in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "Parser.fsy"
                                                                               _1 @ _3 
                   )
# 56 "Parser.fsy"
                 : 'gentype_decn));
|]
# 464 "Parser.fs"
let tables : FSharp.Text.Parsing.Tables<_> = 
  { reductions = _fsyacc_reductions.Value;
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 19;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = tables.Interpret(lexer, lexbuf, startState)
let prog lexer lexbuf : SVProject1.Ast.Program =
    engine lexer lexbuf 0 :?> _
